version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  zookeeper-ui:
    image: elkozmon/zoonavigator
    environment:
      HTTP_PORT: 9000
      AUTO_CONNECT_CONNECTION_STRING: zookeeper:2181
    ports:
      - "9000:9000"
